version: '3.8'

services:
  app:
    build: ./docker
    volumes:
      - ./:/app
      - ./docker/entrypoint.sh:/entrypoint.sh
    working_dir: /app
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=notification_service
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
